use users

create table companies (
	id INT,
	company VARCHAR(50),
	city VARCHAR(50),
	office_address VARCHAR(50)
);
insert into companies (id, company, city, office_address) values (1, 'Rhyloo', 'Aubervilliers', '419 Haas Parkway');
insert into companies (id, company, city, office_address) values (2, 'Yodo', 'Xinglongchang', '364 Lawn Drive');
insert into companies (id, company, city, office_address) values (3, 'Divanoodle', 'Sumurgung', '5 New Castle Point');
insert into companies (id, company, city, office_address) values (4, 'Lajo', 'Palmas', '16415 Hazelcrest Lane');
insert into companies (id, company, city, office_address) values (5, 'Wikizz', 'Saratov', '00 Esch Court');
insert into companies (id, company, city, office_address) values (6, 'Meembee', 'Sawang Daen Din', '01268 Sullivan Junction');
insert into companies (id, company, city, office_address) values (7, 'Blogtag', 'San Francisco', '89324 Straubel Way');
insert into companies (id, company, city, office_address) values (8, 'Trilith', 'Daishan', '03 Summerview Crossing');
insert into companies (id, company, city, office_address) values (9, 'Janyx', 'Salvador', '942 Prairieview Circle');
insert into companies (id, company, city, office_address) values (10, 'Mynte', 'Baorixile', '6 Messerschmidt Circle');
insert into companies (id, company, city, office_address) values (11, 'Oyoloo', 'Eaton', '64 Elgar Plaza');
insert into companies (id, company, city, office_address) values (12, 'Topiclounge', 'Saint-Malo', '4929 Kenwood Trail');
insert into companies (id, company, city, office_address) values (13, 'Edgeblab', 'Dalsjöfors', '80 Maple Hill');
insert into companies (id, company, city, office_address) values (14, 'Brightbean', 'Sukadana', '987 Blaine Circle');
insert into companies (id, company, city, office_address) values (15, 'Twimm', 'Novi Sad', '0 Starling Street');
insert into companies (id, company, city, office_address) values (16, 'Ntags', 'Siukh', '2 Algoma Hill');
insert into companies (id, company, city, office_address) values (17, 'Aimbu', 'Ballisodare', '728 Waywood Crossing');
insert into companies (id, company, city, office_address) values (18, 'Oyoloo', 'As Saddah', '2022 Eagle Crest Alley');
insert into companies (id, company, city, office_address) values (19, 'Bluezoom', 'Fengmu', '09 Northfield Center');
insert into companies (id, company, city, office_address) values (20, 'Meemm', 'Pamplona', '025 Haas Way');
insert into companies (id, company, city, office_address) values (21, 'Innojam', 'Cambebba', '5 Doe Crossing Junction');
insert into companies (id, company, city, office_address) values (22, 'Avaveo', 'Chartres', '78676 Grayhawk Terrace');
insert into companies (id, company, city, office_address) values (23, 'Skyba', 'Al Khushnīyah', '1 Crowley Terrace');
insert into companies (id, company, city, office_address) values (24, 'Thoughtmix', 'Río de Oro', '4223 Larry Plaza');
insert into companies (id, company, city, office_address) values (25, 'Jabberbean', 'Sandakan', '29 Kennedy Junction');
insert into companies (id, company, city, office_address) values (26, 'Skiptube', 'Nässjö', '681 Northport Way');
insert into companies (id, company, city, office_address) values (27, 'Skilith', 'Adela', '7 Armistice Parkway');
insert into companies (id, company, city, office_address) values (28, 'Trilia', 'Tselinnoye', '148 Twin Pines Trail');
insert into companies (id, company, city, office_address) values (29, 'Youtags', 'Matanzas', '652 Lunder Drive');
insert into companies (id, company, city, office_address) values (30, 'Abatz', 'Poli', '65 Stuart Lane');
insert into companies (id, company, city, office_address) values (31, 'Tagchat', 'Los Pinos', '533 Dryden Place');
insert into companies (id, company, city, office_address) values (32, 'Yodo', 'Quận Phú Nhuận', '83581 Superior Parkway');
insert into companies (id, company, city, office_address) values (33, 'Thoughtstorm', 'Bāniyās', '2991 Shasta Drive');
insert into companies (id, company, city, office_address) values (34, 'Buzzster', 'Tuofeng', '24273 Menomonie Way');
insert into companies (id, company, city, office_address) values (35, 'Devpulse', 'Desa Borogojol', '5 Columbus Place');
insert into companies (id, company, city, office_address) values (36, 'Fivespan', 'Jingnao', '27419 Continental Crossing');
insert into companies (id, company, city, office_address) values (37, 'Tagpad', 'Shingū', '2522 Hanover Circle');
insert into companies (id, company, city, office_address) values (38, 'Babbleset', 'Talisayan', '30451 Mcbride Terrace');
insert into companies (id, company, city, office_address) values (39, 'Blognation', 'Carot', '32 Judy Junction');
insert into companies (id, company, city, office_address) values (40, 'Quinu', 'Pinhal Novo', '270 Lake View Center');
insert into companies (id, company, city, office_address) values (41, 'Rhyzio', 'Hetoudian', '20 Farragut Way');
insert into companies (id, company, city, office_address) values (42, 'Babblestorm', 'Dikhil', '433 Dahle Hill');
insert into companies (id, company, city, office_address) values (43, 'Innojam', 'Biru', '7 Michigan Point');
insert into companies (id, company, city, office_address) values (44, 'Photojam', 'Karangpawitan', '9474 Hansons Street');
insert into companies (id, company, city, office_address) values (45, 'Shuffledrive', 'Shuigou’ao', '7443 7th Point');
insert into companies (id, company, city, office_address) values (46, 'Zazio', 'Xiangjiazhai', '316 Mandrake Lane');
insert into companies (id, company, city, office_address) values (47, 'Buzzster', 'Baliuag', '868 Dunning Plaza');
insert into companies (id, company, city, office_address) values (48, 'Flashpoint', 'Lianzhu', '57 Homewood Hill');
insert into companies (id, company, city, office_address) values (49, 'Buzzster', 'Linares', '58397 Bashford Place');
insert into companies (id, company, city, office_address) values (50, 'Linkbridge', 'El Limon', '84229 Mayfield Place');
insert into companies (id, company, city, office_address) values (51, 'Photobug', 'Uruaçu', '64469 Scoville Lane');
insert into companies (id, company, city, office_address) values (52, 'Wikivu', 'Fenshui', '798 Village Green Park');
insert into companies (id, company, city, office_address) values (53, 'Podcat', 'Bom Jesus da Lapa', '2317 Gulseth Trail');
insert into companies (id, company, city, office_address) values (54, 'Voomm', 'Arlöv', '44823 Continental Pass');
insert into companies (id, company, city, office_address) values (55, 'Gabcube', 'Gaimán', '8 Northridge Lane');
insert into companies (id, company, city, office_address) values (56, 'Brainbox', 'Turmi', '7 Shelley Plaza');
insert into companies (id, company, city, office_address) values (57, 'Zooxo', 'Nossa Senhora da Glória', '9 Larry Way');
insert into companies (id, company, city, office_address) values (58, 'Ntags', 'Bagorejo', '4370 Hansons Parkway');
insert into companies (id, company, city, office_address) values (59, 'Minyx', 'Vojnić', '5401 Esker Lane');
insert into companies (id, company, city, office_address) values (60, 'Oyoloo', 'Księżpol', '345 Lindbergh Place');
insert into companies (id, company, city, office_address) values (61, 'Jabbersphere', 'Göteborg', '3748 Dottie Alley');
insert into companies (id, company, city, office_address) values (62, 'Fanoodle', 'Gongju', '3822 Tomscot Road');
insert into companies (id, company, city, office_address) values (63, 'Vidoo', 'Aston', '729 Birchwood Plaza');
insert into companies (id, company, city, office_address) values (64, 'Ntags', 'Florida', '08 Clyde Gallagher Avenue');
insert into companies (id, company, city, office_address) values (65, 'Jazzy', 'Japerejo', '960 Lyons Center');
insert into companies (id, company, city, office_address) values (66, 'Jaxnation', 'Gala', '26 Nancy Hill');
insert into companies (id, company, city, office_address) values (67, 'Photobug', 'Shakhty', '994 Cascade Plaza');
insert into companies (id, company, city, office_address) values (68, 'Brainbox', 'Loanda', '49777 Fieldstone Point');
insert into companies (id, company, city, office_address) values (69, 'Lazz', 'Panognawan', '85 Anderson Crossing');
insert into companies (id, company, city, office_address) values (70, 'Twiyo', 'Vargem Grande Paulista', '28022 Pennsylvania Street');
insert into companies (id, company, city, office_address) values (71, 'Shuffletag', 'Parramos', '57 Grover Junction');
insert into companies (id, company, city, office_address) values (72, 'Jaloo', 'Tumba', '23 Northwestern Park');
insert into companies (id, company, city, office_address) values (73, 'Gabspot', 'Amagarapati', '20791 Autumn Leaf Hill');
insert into companies (id, company, city, office_address) values (74, 'Oodoo', 'Sikonge', '82155 Bayside Street');
insert into companies (id, company, city, office_address) values (75, 'Skyndu', 'Bitung', '59 Eastlawn Alley');
insert into companies (id, company, city, office_address) values (76, 'Vidoo', 'Lidköping', '28 Pond Hill');
insert into companies (id, company, city, office_address) values (77, 'Dabvine', 'Ţayyibat al Imām', '23080 Northridge Drive');
insert into companies (id, company, city, office_address) values (78, 'Buzzbean', 'Ichinohe', '1 Macpherson Alley');
insert into companies (id, company, city, office_address) values (79, 'Meembee', 'Barra Bonita', '0526 Steensland Center');
insert into companies (id, company, city, office_address) values (80, 'Pixoboo', 'Abuko', '528 New Castle Point');
insert into companies (id, company, city, office_address) values (81, 'Brainsphere', 'Talpe', '927 Talisman Crossing');
insert into companies (id, company, city, office_address) values (82, 'Oba', 'Anguera', '6835 Del Sol Road');
insert into companies (id, company, city, office_address) values (83, 'Dabfeed', 'Sagaing', '911 Arrowood Alley');
insert into companies (id, company, city, office_address) values (84, 'Tazz', 'Berat', '6 Thierer Circle');
insert into companies (id, company, city, office_address) values (85, 'Tavu', 'Nikol’sk', '79 Pierstorff Parkway');
insert into companies (id, company, city, office_address) values (86, 'Yata', 'Staroderevyankovskaya', '74 Nancy Place');
insert into companies (id, company, city, office_address) values (87, 'Topdrive', 'Ōtsu-shi', '17 Nova Point');
insert into companies (id, company, city, office_address) values (88, 'Vitz', 'Denver', '95 Spaight Terrace');
insert into companies (id, company, city, office_address) values (89, 'Dazzlesphere', 'Kanugrahan', '90 Portage Point');
insert into companies (id, company, city, office_address) values (90, 'Skyba', 'Dayu', '1321 South Center');
insert into companies (id, company, city, office_address) values (91, 'Gabtype', 'Nanfeng', '91 Gateway Parkway');
insert into companies (id, company, city, office_address) values (92, 'Skinder', 'Konyshevka', '2468 Di Loreto Avenue');
insert into companies (id, company, city, office_address) values (93, 'Riffwire', 'Šentrupert', '29276 Gale Street');
insert into companies (id, company, city, office_address) values (94, 'Babbleblab', 'Jinlong', '660 Kennedy Junction');
insert into companies (id, company, city, office_address) values (95, 'Yoveo', 'Jimaguayú', '267 Sunnyside Pass');
insert into companies (id, company, city, office_address) values (96, 'Eare', 'Yong’an', '337 Harbort Pass');
insert into companies (id, company, city, office_address) values (97, 'Thoughtworks', 'Nantes', '1886 Lindbergh Way');
insert into companies (id, company, city, office_address) values (98, 'Linkbridge', 'Hofors', '406 Bowman Avenue');
insert into companies (id, company, city, office_address) values (99, 'Trunyx', 'Bendorubuh', '61952 Corscot Court');
insert into companies (id, company, city, office_address) values (100, 'Riffwire', 'Próchoma', '949 Anderson Lane');
insert into companies (id, company, city, office_address) values (101, 'Blogtags', 'Llanera', '2287 Florence Plaza');
insert into companies (id, company, city, office_address) values (102, 'Gigaclub', 'Pergamino', '995 Riverside Center');
insert into companies (id, company, city, office_address) values (103, 'Riffpedia', 'Zhongshan', '1 Beilfuss Lane');
insert into companies (id, company, city, office_address) values (104, 'Realbuzz', 'Pagelaran', '5094 Hanson Hill');
insert into companies (id, company, city, office_address) values (105, 'Browsezoom', 'Taksimo', '087 Warner Center');
insert into companies (id, company, city, office_address) values (106, 'Edgeclub', 'Krajan', '559 Anthes Court');
insert into companies (id, company, city, office_address) values (107, 'Quamba', 'Karbunara e Vogël', '5105 Basil Lane');
insert into companies (id, company, city, office_address) values (108, 'Yodel', 'Nariño', '27309 Bluejay Terrace');
insert into companies (id, company, city, office_address) values (109, 'Pixoboo', 'Kyonju', '02022 Sunfield Circle');
insert into companies (id, company, city, office_address) values (110, 'Eazzy', 'Suwatu', '4 Crescent Oaks Drive');
insert into companies (id, company, city, office_address) values (111, 'Skyble', 'Komiža', '09 Hallows Pass');
insert into companies (id, company, city, office_address) values (112, 'Janyx', 'Colorado Springs', '6 Anderson Drive');
insert into companies (id, company, city, office_address) values (113, 'Brainsphere', 'Bebedahan', '3 Dwight Street');
insert into companies (id, company, city, office_address) values (114, 'Devcast', 'Yudaikelike', '81810 Cambridge Lane');
insert into companies (id, company, city, office_address) values (115, 'Vipe', 'Slavgorod', '461 Sullivan Street');
insert into companies (id, company, city, office_address) values (116, 'Kwinu', 'Duifang', '0423 Dennis Street');
insert into companies (id, company, city, office_address) values (117, 'Mymm', 'Funchalinho', '6 Stone Corner Way');
insert into companies (id, company, city, office_address) values (118, 'Realbridge', 'Gagah', '98865 Green Ridge Crossing');
insert into companies (id, company, city, office_address) values (119, 'Voomm', 'Al Ghizlānīyah', '4 Mallard Way');
insert into companies (id, company, city, office_address) values (120, 'Fliptune', 'Pouébo', '1 Anzinger Plaza');
insert into companies (id, company, city, office_address) values (121, 'Kanoodle', 'Thị Trấn Phù Yên', '83 Crowley Plaza');
insert into companies (id, company, city, office_address) values (122, 'Photobug', 'Uherské Hradiště', '62 Lindbergh Parkway');
insert into companies (id, company, city, office_address) values (123, 'Skipstorm', 'Saint-Marcellin', '90 Forest Street');
insert into companies (id, company, city, office_address) values (124, 'Linkbridge', 'Mashan', '49185 Mariners Cove Alley');
insert into companies (id, company, city, office_address) values (125, 'Linktype', 'Sridadi', '94915 Warner Trail');
insert into companies (id, company, city, office_address) values (126, 'Fivespan', 'København', '59434 Elgar Hill');
insert into companies (id, company, city, office_address) values (127, 'Blogpad', 'Port-aux-Français', '2138 Hanover Pass');
insert into companies (id, company, city, office_address) values (128, 'Photojam', 'Sanpai', '7 Pawling Point');
insert into companies (id, company, city, office_address) values (129, 'Linklinks', 'Pugeran', '2 Sheridan Lane');
insert into companies (id, company, city, office_address) values (130, 'Kayveo', 'Balud', '14 Mallory Trail');
insert into companies (id, company, city, office_address) values (131, 'Blogpad', 'Molteno', '0 Thackeray Street');
insert into companies (id, company, city, office_address) values (132, 'Gabtype', 'Michałów', '37 Mccormick Park');
insert into companies (id, company, city, office_address) values (133, 'Tanoodle', 'Jasaan', '63006 Rowland Place');
insert into companies (id, company, city, office_address) values (134, 'Vidoo', 'Angatel', '2726 Eastwood Plaza');
insert into companies (id, company, city, office_address) values (135, 'Feedmix', 'Zhouxi', '6 Oakridge Street');
insert into companies (id, company, city, office_address) values (136, 'Agimba', 'Działoszyce', '8311 Waxwing Court');
insert into companies (id, company, city, office_address) values (137, 'Janyx', 'Kraaifontein', '37 Hanover Park');
insert into companies (id, company, city, office_address) values (138, 'Flipbug', 'Simpang', '9998 Cambridge Junction');
insert into companies (id, company, city, office_address) values (139, 'Trilia', 'Seversk', '7 Arrowood Street');
insert into companies (id, company, city, office_address) values (140, 'Thoughtbridge', 'Perdões', '0985 Kim Place');
insert into companies (id, company, city, office_address) values (141, 'Reallinks', 'Tlogosadang', '16 Mcbride Crossing');
insert into companies (id, company, city, office_address) values (142, 'Rhybox', 'Zhouzhuang', '1313 Dayton Junction');
insert into companies (id, company, city, office_address) values (143, 'Kamba', 'Gasa', '2 Anniversary Alley');
insert into companies (id, company, city, office_address) values (144, 'Buzzshare', 'Liang', '46534 Corry Junction');
insert into companies (id, company, city, office_address) values (145, 'Zoozzy', 'Foča', '9 Pennsylvania Circle');
insert into companies (id, company, city, office_address) values (146, 'Jatri', 'Karsin', '98 Brickson Park Drive');
insert into companies (id, company, city, office_address) values (147, 'Youtags', 'Oslo', '0867 Caliangt Junction');
insert into companies (id, company, city, office_address) values (148, 'Edgeblab', 'Chřibská', '8 Eastwood Drive');
insert into companies (id, company, city, office_address) values (149, 'Jabberstorm', 'Subotica', '89984 Utah Center');
insert into companies (id, company, city, office_address) values (150, 'Zooveo', 'Fangxiang', '337 Bobwhite Point');
insert into companies (id, company, city, office_address) values (151, 'Quimba', 'Savski Venac', '86091 Shoshone Way');
insert into companies (id, company, city, office_address) values (152, 'Kayveo', 'Kynopiástes', '76310 Lakeland Point');
insert into companies (id, company, city, office_address) values (153, 'Kamba', 'Hobo', '3497 Manufacturers Junction');
insert into companies (id, company, city, office_address) values (154, 'Digitube', 'Lopez Jaena', '344 Bellgrove Trail');
insert into companies (id, company, city, office_address) values (155, 'Skynoodle', 'Dębno', '8 Kingsford Court');
insert into companies (id, company, city, office_address) values (156, 'Brainbox', 'Cemplang', '474 Melody Court');
insert into companies (id, company, city, office_address) values (157, 'Flipopia', 'Tangnanzhen', '14808 Packers Plaza');
insert into companies (id, company, city, office_address) values (158, 'Zoonder', 'Ra’s Bayrūt', '876 Maple Alley');
insert into companies (id, company, city, office_address) values (159, 'Topicshots', 'Bang Khon Thi', '960 Golden Leaf Avenue');
insert into companies (id, company, city, office_address) values (160, 'Tavu', 'Tangfang', '36 Laurel Terrace');
insert into companies (id, company, city, office_address) values (161, 'Fanoodle', 'Kallithéa', '7 Anzinger Parkway');
insert into companies (id, company, city, office_address) values (162, 'Eimbee', 'Cortinhas', '6 Harper Parkway');
insert into companies (id, company, city, office_address) values (163, 'Tagtune', 'Kungsbacka', '89038 Sloan Center');
insert into companies (id, company, city, office_address) values (164, 'Agimba', 'Krajan', '48 Johnson Center');
insert into companies (id, company, city, office_address) values (165, 'Quatz', 'Loja', '2 Linden Alley');
insert into companies (id, company, city, office_address) values (166, 'Vimbo', 'Kuntong', '9 Lukken Street');
insert into companies (id, company, city, office_address) values (167, 'Agivu', 'Nong Bua Lamphu', '32 Center Hill');
insert into companies (id, company, city, office_address) values (168, 'Demizz', 'Lanjaghbyur', '895 Kinsman Drive');
insert into companies (id, company, city, office_address) values (169, 'Kwilith', 'Gorskaya', '31901 Nova Junction');
insert into companies (id, company, city, office_address) values (170, 'Jetpulse', 'Khlong Toei', '5 Nelson Plaza');
insert into companies (id, company, city, office_address) values (171, 'Voonte', 'Daweishan', '5339 Delladonna Trail');
insert into companies (id, company, city, office_address) values (172, 'Realbridge', 'Pridraga', '8152 Homewood Junction');
insert into companies (id, company, city, office_address) values (173, 'Realbuzz', 'Al ‘Anān', '23450 Londonderry Point');
insert into companies (id, company, city, office_address) values (174, 'Rhyloo', 'Terenozek', '231 Bay Avenue');
insert into companies (id, company, city, office_address) values (175, 'Shufflebeat', 'Bangbayang Kaler', '5666 Barnett Trail');
insert into companies (id, company, city, office_address) values (176, 'Zooveo', 'Bila Tserkva', '37254 Texas Circle');
insert into companies (id, company, city, office_address) values (177, 'Rooxo', 'Baocun', '43 Kenwood Junction');
insert into companies (id, company, city, office_address) values (178, 'Youspan', 'Cantapoy', '13 Debs Plaza');
insert into companies (id, company, city, office_address) values (179, 'Gevee', 'Acolla', '73 American Parkway');
insert into companies (id, company, city, office_address) values (180, 'Mynte', 'Platagata', '9777 Park Meadow Street');
insert into companies (id, company, city, office_address) values (181, 'Fliptune', 'Matingain', '35876 Summit Circle');
insert into companies (id, company, city, office_address) values (182, 'Trilith', 'Taraco', '3576 Mccormick Alley');
insert into companies (id, company, city, office_address) values (183, 'Leenti', 'Camocim', '455 Gale Circle');
insert into companies (id, company, city, office_address) values (184, 'Topdrive', 'Sokol', '3 Warrior Way');
insert into companies (id, company, city, office_address) values (185, 'Skivee', 'Dungon', '3159 Duke Place');
insert into companies (id, company, city, office_address) values (186, 'Jabbertype', 'Canalete', '2 Eagan Place');
insert into companies (id, company, city, office_address) values (187, 'Blogtag', 'Kuznetsovs’k', '9 Stang Terrace');
insert into companies (id, company, city, office_address) values (188, 'Dabfeed', 'Maoyang', '1086 Commercial Way');
insert into companies (id, company, city, office_address) values (189, 'Oyonder', 'Jalanbaru', '54 Fuller Crossing');
insert into companies (id, company, city, office_address) values (190, 'Twitterbeat', 'Puno', '2690 Hintze Way');
insert into companies (id, company, city, office_address) values (191, 'Edgeify', 'Vesoul', '160 Dennis Avenue');
insert into companies (id, company, city, office_address) values (192, 'Dazzlesphere', 'Boston', '98950 Warrior Junction');
insert into companies (id, company, city, office_address) values (193, 'Jazzy', 'Nueva Loja', '32 Hansons Parkway');
insert into companies (id, company, city, office_address) values (194, 'Edgepulse', 'Sidayu', '335 Carpenter Alley');
insert into companies (id, company, city, office_address) values (195, 'Photofeed', 'Xaysetha', '0145 Monterey Pass');
insert into companies (id, company, city, office_address) values (196, 'Twimm', 'Tamot', '3420 Rutledge Center');
insert into companies (id, company, city, office_address) values (197, 'Tekfly', 'Qingshui', '5111 Old Gate Avenue');
insert into companies (id, company, city, office_address) values (198, 'Oyonder', 'Quartier Morin', '0172 West Street');
insert into companies (id, company, city, office_address) values (199, 'Dynabox', 'Vairão', '8334 Scott Place');
insert into companies (id, company, city, office_address) values (200, 'Blogspan', 'Bongsri', '64515 Homewood Way');
insert into companies (id, company, city, office_address) values (201, 'LiveZ', 'Néa Magnisía', '4 Brentwood Terrace');
insert into companies (id, company, city, office_address) values (202, 'Eimbee', 'Araguari', '72703 Lakeland Park');
insert into companies (id, company, city, office_address) values (203, 'Wordpedia', 'Yisuhe', '47766 Schiller Crossing');
insert into companies (id, company, city, office_address) values (204, 'Yodo', 'Żelazków', '5 Scott Road');
insert into companies (id, company, city, office_address) values (205, 'Jazzy', 'Västra Frölunda', '77 Westport Court');
insert into companies (id, company, city, office_address) values (206, 'Meezzy', 'Dongsheng', '19 Mockingbird Parkway');
insert into companies (id, company, city, office_address) values (207, 'Twitterbridge', 'Saint-Claude', '827 Clyde Gallagher Road');
insert into companies (id, company, city, office_address) values (208, 'Skimia', 'Chapayevka', '041 Artisan Drive');
insert into companies (id, company, city, office_address) values (209, 'Miboo', 'Tô Hạp', '96891 Monument Lane');
insert into companies (id, company, city, office_address) values (210, 'Rhyzio', 'Tekes', '98 Corscot Lane');
insert into companies (id, company, city, office_address) values (211, 'Dablist', 'Orlando', '061 Anniversary Street');
insert into companies (id, company, city, office_address) values (212, 'Skiba', 'Daegu', '2 Warbler Trail');
insert into companies (id, company, city, office_address) values (213, 'JumpXS', 'Shchukino', '2561 Messerschmidt Hill');
insert into companies (id, company, city, office_address) values (214, 'Flashset', 'Kinmparana', '25944 Rusk Hill');
insert into companies (id, company, city, office_address) values (215, 'Oyoyo', 'Kasturi', '5 Haas Parkway');
insert into companies (id, company, city, office_address) values (216, 'Skimia', 'Uthal', '1 Ilene Park');
insert into companies (id, company, city, office_address) values (217, 'Vitz', 'Kimovsk', '07145 Redwing Place');
insert into companies (id, company, city, office_address) values (218, 'Gabcube', 'Jatinagara', '65 Scott Trail');
insert into companies (id, company, city, office_address) values (219, 'Dabjam', 'Ichinohe', '973 Florence Lane');
insert into companies (id, company, city, office_address) values (220, 'Topicblab', 'Luci', '0209 Stang Avenue');
insert into companies (id, company, city, office_address) values (221, 'Kamba', 'Almafuerte', '7 Independence Center');
insert into companies (id, company, city, office_address) values (222, 'Plajo', 'Manique', '598 Eliot Drive');
insert into companies (id, company, city, office_address) values (223, 'Thoughtbridge', 'Hagonoy', '06 Bowman Circle');
insert into companies (id, company, city, office_address) values (224, 'Camimbo', 'Zhongmen', '78683 Jana Center');
insert into companies (id, company, city, office_address) values (225, 'Zooveo', 'San Rafael', '57 Mockingbird Center');
insert into companies (id, company, city, office_address) values (226, 'Rhynoodle', 'Kaavi', '2537 Magdeline Way');
insert into companies (id, company, city, office_address) values (227, 'Trilith', 'Springfield', '89 Sutherland Point');
insert into companies (id, company, city, office_address) values (228, 'Edgetag', 'Primero de Mayo', '5 Vahlen Drive');
insert into companies (id, company, city, office_address) values (229, 'Fanoodle', 'Fotolívos', '36 Sheridan Road');
insert into companies (id, company, city, office_address) values (230, 'Twitterbeat', 'Tosu', '42879 Mitchell Place');
insert into companies (id, company, city, office_address) values (231, 'Tagchat', 'Ubatuba', '134 Graceland Trail');
insert into companies (id, company, city, office_address) values (232, 'Jaloo', 'Laiyuan', '85 Stone Corner Point');
insert into companies (id, company, city, office_address) values (233, 'Teklist', 'Dokri', '488 East Court');
insert into companies (id, company, city, office_address) values (234, 'Divanoodle', 'Pasadena', '56909 School Street');
insert into companies (id, company, city, office_address) values (235, 'Trudeo', 'Kalininaul', '1752 Boyd Hill');
insert into companies (id, company, city, office_address) values (236, 'Gigazoom', 'Krasnohrad', '2857 Butternut Place');
insert into companies (id, company, city, office_address) values (237, 'Cogilith', 'Gradec', '0 Sutteridge Crossing');
insert into companies (id, company, city, office_address) values (238, 'Twinte', 'Chamical', '8 Eagan Crossing');
insert into companies (id, company, city, office_address) values (239, 'Myworks', 'Ang Thong', '9073 Loomis Parkway');
insert into companies (id, company, city, office_address) values (240, 'Photobug', 'Andres Bonifacio', '404 Anhalt Point');
insert into companies (id, company, city, office_address) values (241, 'Meezzy', 'Beigang', '9400 Grim Center');
insert into companies (id, company, city, office_address) values (242, 'Babbleblab', 'Stakhanov', '11377 Messerschmidt Plaza');
insert into companies (id, company, city, office_address) values (243, 'Devshare', 'Tacoma', '8210 Shoshone Terrace');
insert into companies (id, company, city, office_address) values (244, 'Demimbu', 'Varnsdorf', '21 Wayridge Plaza');
insert into companies (id, company, city, office_address) values (245, 'Camido', 'Yaozhuang', '18 Schmedeman Place');
insert into companies (id, company, city, office_address) values (246, 'Photospace', 'Campechuela', '08382 Dunning Plaza');
insert into companies (id, company, city, office_address) values (247, 'Avamba', 'Moret-sur-Loing', '86 Anthes Alley');
insert into companies (id, company, city, office_address) values (248, 'Zoomzone', 'Zoumaling', '031 Summerview Circle');
insert into companies (id, company, city, office_address) values (249, 'Feedfish', 'Canala', '5698 Sauthoff Point');
insert into companies (id, company, city, office_address) values (250, 'Realblab', 'Eskilstuna', '19898 Mayfield Junction');
insert into companies (id, company, city, office_address) values (251, 'Babbleset', 'Tinampo', '50870 Buhler Trail');
insert into companies (id, company, city, office_address) values (252, 'Fivechat', 'Lopar', '1999 Macpherson Terrace');
insert into companies (id, company, city, office_address) values (253, 'Yozio', 'Fada', '4443 Evergreen Plaza');
insert into companies (id, company, city, office_address) values (254, 'Realmix', 'Cengjia', '4039 Hallows Trail');
insert into companies (id, company, city, office_address) values (255, 'Topiclounge', 'Cheyenne', '96348 Elka Pass');
insert into companies (id, company, city, office_address) values (256, 'Katz', 'Phonsavan', '90109 International Junction');
insert into companies (id, company, city, office_address) values (257, 'Babbleopia', 'Aristóbulo del Valle', '94 Vermont Place');
insert into companies (id, company, city, office_address) values (258, 'Meembee', 'Ketian', '17 Melby Way');
insert into companies (id, company, city, office_address) values (259, 'Thoughtbridge', 'Fengmu', '497 Gulseth Parkway');
insert into companies (id, company, city, office_address) values (260, 'Oozz', 'Bazha', '3 Hazelcrest Junction');
insert into companies (id, company, city, office_address) values (261, 'Linktype', 'Mizur', '461 Mayer Hill');
insert into companies (id, company, city, office_address) values (262, 'Mymm', 'Birinci Aşıqlı', '7034 Del Sol Place');
insert into companies (id, company, city, office_address) values (263, 'Devshare', 'Guandu', '2 Meadow Ridge Road');
insert into companies (id, company, city, office_address) values (264, 'Dabjam', 'Nagasari', '82 Oak Valley Alley');
insert into companies (id, company, city, office_address) values (265, 'Brainbox', 'Folques', '6771 Erie Way');
insert into companies (id, company, city, office_address) values (266, 'Viva', 'Guaymango', '3 Hagan Hill');
insert into companies (id, company, city, office_address) values (267, 'Skibox', 'Atyrau', '76 Randy Point');
insert into companies (id, company, city, office_address) values (268, 'Twinte', 'Joliet', '9 Glendale Terrace');
insert into companies (id, company, city, office_address) values (269, 'Gabcube', 'Marseille', '587 Browning Center');
insert into companies (id, company, city, office_address) values (270, 'Blogtag', 'Kuty', '52156 Fallview Way');
insert into companies (id, company, city, office_address) values (271, 'Youtags', 'Poctol', '53114 Kennedy Road');
insert into companies (id, company, city, office_address) values (272, 'Brightbean', 'Ibara', '37 Spohn Road');
insert into companies (id, company, city, office_address) values (273, 'Lajo', 'Kadudampit', '649 North Lane');
insert into companies (id, company, city, office_address) values (274, 'Quatz', 'Raheny', '74 Surrey Parkway');
insert into companies (id, company, city, office_address) values (275, 'Agimba', 'Yamaguchi-shi', '23 Vidon Point');
insert into companies (id, company, city, office_address) values (276, 'Photobug', 'Amānzī', '72 Fremont Center');
insert into companies (id, company, city, office_address) values (277, 'Flashspan', 'Mooirivier', '4377 Hooker Point');
insert into companies (id, company, city, office_address) values (278, 'Wordware', 'Thanh Nê', '95885 Fulton Trail');
insert into companies (id, company, city, office_address) values (279, 'Quaxo', 'Binafun', '825 Onsgard Hill');
insert into companies (id, company, city, office_address) values (280, 'Thoughtbridge', 'Achiaman', '7525 Westerfield Drive');
insert into companies (id, company, city, office_address) values (281, 'Zoomcast', 'Sadang Kulon', '5 Brentwood Way');
insert into companies (id, company, city, office_address) values (282, 'Dabshots', 'Suai', '0012 Schiller Drive');
insert into companies (id, company, city, office_address) values (283, 'Babbleblab', 'Arras', '241 Green Ridge Hill');
insert into companies (id, company, city, office_address) values (284, 'Fadeo', 'Hamburg', '3702 Moose Street');
insert into companies (id, company, city, office_address) values (285, 'Tavu', 'Yajiang', '745 Steensland Street');
insert into companies (id, company, city, office_address) values (286, 'Fivebridge', 'Zouma', '6923 Eastwood Plaza');
insert into companies (id, company, city, office_address) values (287, 'Buzzbean', 'Maguan', '1401 Kings Road');
insert into companies (id, company, city, office_address) values (288, 'Babbleset', 'Kacangan Lor', '90 Brickson Park Junction');
insert into companies (id, company, city, office_address) values (289, 'Brainverse', 'Culeng', '28 Dawn Place');
insert into companies (id, company, city, office_address) values (290, 'Ntags', 'Bator', '2432 Hoepker Point');
insert into companies (id, company, city, office_address) values (291, 'Mycat', 'Aldergrove', '6 Buhler Place');
insert into companies (id, company, city, office_address) values (292, 'Meeveo', 'Nogueira do Cravo', '21 Meadow Ridge Crossing');
insert into companies (id, company, city, office_address) values (293, 'Quimba', 'Taltal', '04 Grayhawk Street');
insert into companies (id, company, city, office_address) values (294, 'Dynabox', 'Budapest', '838 Mallory Point');
insert into companies (id, company, city, office_address) values (295, 'Kamba', 'Strenči', '1061 Loomis Plaza');
insert into companies (id, company, city, office_address) values (296, 'Teklist', 'Mizusawa', '0193 Sheridan Crossing');
insert into companies (id, company, city, office_address) values (297, 'Yadel', 'Kuragaki-kosugi', '82 Park Meadow Junction');
insert into companies (id, company, city, office_address) values (298, 'Yotz', 'Xiantang', '13952 Center Road');
insert into companies (id, company, city, office_address) values (299, 'Flashpoint', 'Charleroi', '12 International Park');
insert into companies (id, company, city, office_address) values (300, 'Devshare', 'Kopong', '3 Anniversary Pass');
insert into companies (id, company, city, office_address) values (301, 'Quire', 'Nantou', '6667 Kensington Way');
insert into companies (id, company, city, office_address) values (302, 'Trunyx', 'Wewit', '91 Vera Court');
insert into companies (id, company, city, office_address) values (303, 'Zoovu', 'Petroúpolis', '9901 Bartillon Plaza');
insert into companies (id, company, city, office_address) values (304, 'Yodel', 'Baisha', '5919 Fremont Court');
insert into companies (id, company, city, office_address) values (305, 'Oloo', 'Ipiales', '6693 Dwight Hill');
insert into companies (id, company, city, office_address) values (306, 'Jetpulse', 'Siguinon', '813 Stang Pass');
insert into companies (id, company, city, office_address) values (307, 'Riffpedia', 'San Andrés', '9 Forster Parkway');
insert into companies (id, company, city, office_address) values (308, 'Midel', 'Sheki', '280 Reindahl Parkway');
insert into companies (id, company, city, office_address) values (309, 'Feedspan', 'Hezhai', '7874 Susan Place');
insert into companies (id, company, city, office_address) values (310, 'Riffpath', 'Novotitarovskaya', '5488 Nelson Lane');
insert into companies (id, company, city, office_address) values (311, 'Abata', 'Alor Setar', '820 Mcguire Junction');
insert into companies (id, company, city, office_address) values (312, 'Thoughtbridge', 'Sukamaju', '076 Westend Terrace');
insert into companies (id, company, city, office_address) values (313, 'Realbuzz', 'Juzhen', '50 Sauthoff Point');
insert into companies (id, company, city, office_address) values (314, 'Skyba', 'Wangge’ertang', '4363 Lillian Parkway');
insert into companies (id, company, city, office_address) values (315, 'Wikizz', 'Pategi', '12302 Portage Way');
insert into companies (id, company, city, office_address) values (316, 'Jatri', 'Santander', '0446 Magdeline Junction');
insert into companies (id, company, city, office_address) values (317, 'Voonyx', 'Kuching', '8 Burning Wood Parkway');
insert into companies (id, company, city, office_address) values (318, 'Devpulse', 'Huancaray', '9673 4th Road');
insert into companies (id, company, city, office_address) values (319, 'Roombo', 'Bollnäs', '0 Esch Hill');
insert into companies (id, company, city, office_address) values (320, 'Twinder', 'Köneürgench', '31 Buell Parkway');
insert into companies (id, company, city, office_address) values (321, 'Yacero', 'Gombang', '684 Buell Trail');
insert into companies (id, company, city, office_address) values (322, 'Quimba', 'Satita', '15308 Garrison Place');
insert into companies (id, company, city, office_address) values (323, 'Buzzster', 'La Troncal', '860 Mifflin Junction');
insert into companies (id, company, city, office_address) values (324, 'Blogpad', 'Amnat Charoen', '2475 Roth Plaza');
insert into companies (id, company, city, office_address) values (325, 'Browsebug', 'Schaumburg', '16 American Ash Plaza');
insert into companies (id, company, city, office_address) values (326, 'Lajo', 'Arlöv', '7321 Pearson Avenue');
insert into companies (id, company, city, office_address) values (327, 'Gabvine', 'Thun', '259 Rowland Parkway');
insert into companies (id, company, city, office_address) values (328, 'Vidoo', 'Kiruna', '84 Magdeline Junction');
insert into companies (id, company, city, office_address) values (329, 'Dablist', 'Ramada', '80543 Claremont Street');
insert into companies (id, company, city, office_address) values (330, 'Centimia', 'Nanyang', '0 Oakridge Park');
insert into companies (id, company, city, office_address) values (331, 'Jabberbean', 'Jingu', '7 Texas Junction');
insert into companies (id, company, city, office_address) values (332, 'Yozio', 'Tejen', '39592 Bluejay Plaza');
insert into companies (id, company, city, office_address) values (333, 'Myworks', 'Tarata', '84 Brickson Park Park');
insert into companies (id, company, city, office_address) values (334, 'Eazzy', 'Malabar', '4 Pawling Drive');
insert into companies (id, company, city, office_address) values (335, 'Yakijo', 'Karangcombong', '393 Derek Alley');
insert into companies (id, company, city, office_address) values (336, 'Kimia', 'Cassanayan', '4 Maple Lane');
insert into companies (id, company, city, office_address) values (337, 'Devcast', 'Santo Domingo', '8 Blue Bill Park Plaza');
insert into companies (id, company, city, office_address) values (338, 'Eare', 'Essen', '6441 Spenser Way');
insert into companies (id, company, city, office_address) values (339, 'Babblestorm', 'Sambogunung', '34 Ludington Parkway');
insert into companies (id, company, city, office_address) values (340, 'Gabvine', 'Cáceres', '67664 Kedzie Hill');
insert into companies (id, company, city, office_address) values (341, 'Dabshots', 'Platičevo', '65 Walton Circle');
insert into companies (id, company, city, office_address) values (342, 'Yakitri', 'Lavradio', '3056 Declaration Pass');
insert into companies (id, company, city, office_address) values (343, 'Blogspan', 'Buenaventura', '76764 Sunfield Lane');
insert into companies (id, company, city, office_address) values (344, 'Cogidoo', 'Tignoan', '43 Buell Way');
insert into companies (id, company, city, office_address) values (345, 'Fanoodle', 'João Pessoa', '11567 Stuart Lane');
insert into companies (id, company, city, office_address) values (346, 'Fliptune', 'Eastern Suburbs Mc', '2 Gateway Avenue');
insert into companies (id, company, city, office_address) values (347, 'Voomm', 'Saint-Dizier', '02 Goodland Road');
insert into companies (id, company, city, office_address) values (348, 'Gigashots', 'Puerto Tejada', '261 Dottie Avenue');
insert into companies (id, company, city, office_address) values (349, 'Jaxspan', 'Boundiali', '1863 Hauk Hill');
insert into companies (id, company, city, office_address) values (350, 'Browsebug', 'Hyesan-dong', '41044 Corben Trail');
insert into companies (id, company, city, office_address) values (351, 'Quamba', 'Ketawang', '908 Forest Run Plaza');
insert into companies (id, company, city, office_address) values (352, 'Quatz', 'Jongorsari', '6 Ryan Street');
insert into companies (id, company, city, office_address) values (353, 'Omba', 'Meaux', '274 Stone Corner Center');
insert into companies (id, company, city, office_address) values (354, 'Jaxspan', 'Brnaze', '80449 Upham Lane');
insert into companies (id, company, city, office_address) values (355, 'Topicware', 'Xingtai', '6508 Dottie Terrace');
insert into companies (id, company, city, office_address) values (356, 'JumpXS', 'El Carmen', '7154 Jenifer Street');
insert into companies (id, company, city, office_address) values (357, 'Livetube', 'Dębe Wielkie', '49 Esker Road');
insert into companies (id, company, city, office_address) values (358, 'Jaxworks', 'Trélissac', '884 Twin Pines Hill');
insert into companies (id, company, city, office_address) values (359, 'Topicshots', 'Urengoy', '9892 Blue Bill Park Lane');
insert into companies (id, company, city, office_address) values (360, 'Centimia', 'Rio Branco do Sul', '63998 Londonderry Circle');
insert into companies (id, company, city, office_address) values (361, 'Flashspan', 'Oslomej', '12466 Banding Way');
insert into companies (id, company, city, office_address) values (362, 'Divanoodle', 'Alagoa Grande', '47 Crescent Oaks Junction');
insert into companies (id, company, city, office_address) values (363, 'Edgepulse', 'Rivesaltes', '1153 Evergreen Crossing');
insert into companies (id, company, city, office_address) values (364, 'Jayo', 'Voždovac', '400 Montana Way');
insert into companies (id, company, city, office_address) values (365, 'Oyope', 'Bomadi', '6 Merrick Point');
insert into companies (id, company, city, office_address) values (366, 'Trupe', 'Rumelange', '474 Atwood Place');
insert into companies (id, company, city, office_address) values (367, 'Skipstorm', 'Zhatay', '0153 Saint Paul Hill');
insert into companies (id, company, city, office_address) values (368, 'Abata', 'Alpedrinha', '41 Pawling Trail');
insert into companies (id, company, city, office_address) values (369, 'Gigashots', 'Lobatse', '1 La Follette Road');
insert into companies (id, company, city, office_address) values (370, 'Kaymbo', 'Penalva de Alva', '0692 Charing Cross Plaza');
insert into companies (id, company, city, office_address) values (371, 'Youfeed', 'Aguada de Pasajeros', '2808 Golf Street');
insert into companies (id, company, city, office_address) values (372, 'Trudeo', 'Dashtobod', '9352 Knutson Park');
insert into companies (id, company, city, office_address) values (373, 'Babbleset', 'Zudun', '36583 Garrison Parkway');
insert into companies (id, company, city, office_address) values (374, 'Mybuzz', 'Gaza', '0 Ridgeway Pass');
insert into companies (id, company, city, office_address) values (375, 'Quimba', 'Cachadinha', '97 Pond Pass');
insert into companies (id, company, city, office_address) values (376, 'Yotz', 'Caracol', '1317 Cambridge Court');
insert into companies (id, company, city, office_address) values (377, 'Oyoloo', 'Smolenskaya', '2062 Fairfield Point');
insert into companies (id, company, city, office_address) values (378, 'Meevee', 'Padej', '60 Transport Way');
insert into companies (id, company, city, office_address) values (379, 'Reallinks', 'Hongqiao', '03 Kingsford Road');
insert into companies (id, company, city, office_address) values (380, 'Youbridge', 'Angelochóri', '7489 Dawn Drive');
insert into companies (id, company, city, office_address) values (381, 'Topiclounge', 'Hayang', '730 High Crossing Terrace');
insert into companies (id, company, city, office_address) values (382, 'Centizu', 'Dubreuil', '7 Elgar Crossing');
insert into companies (id, company, city, office_address) values (383, 'Centizu', 'Stony Plain', '5 Ludington Street');
insert into companies (id, company, city, office_address) values (384, 'Leexo', 'Zhongcheng', '2 Walton Park');
insert into companies (id, company, city, office_address) values (385, 'Vipe', 'Lubu', '388 Oak Parkway');
insert into companies (id, company, city, office_address) values (386, 'Jaxbean', 'Põlva', '3 Lotheville Hill');
insert into companies (id, company, city, office_address) values (387, 'Yakidoo', 'Sanghan', '019 Oriole Alley');
insert into companies (id, company, city, office_address) values (388, 'Tagtune', 'Las Palomas', '44 Northwestern Pass');
insert into companies (id, company, city, office_address) values (389, 'Katz', 'Jam', '60558 7th Alley');
insert into companies (id, company, city, office_address) values (390, 'Topdrive', 'RMI Capitol', '93914 Killdeer Trail');
insert into companies (id, company, city, office_address) values (391, 'Yodel', 'Nanyuan', '1123 Derek Avenue');
insert into companies (id, company, city, office_address) values (392, 'Teklist', 'Sainte-Marthe-sur-le-Lac', '84153 Kim Point');
insert into companies (id, company, city, office_address) values (393, 'Thoughtstorm', 'Pszczew', '0654 Springview Court');
insert into companies (id, company, city, office_address) values (394, 'Twimm', 'Decatur', '2 Cody Junction');
insert into companies (id, company, city, office_address) values (395, 'Realbuzz', 'Minnedosa', '590 Transport Court');
insert into companies (id, company, city, office_address) values (396, 'Twitterbeat', 'Bronkhorstspruit', '1967 Algoma Terrace');
insert into companies (id, company, city, office_address) values (397, 'Babblestorm', 'Świętajno', '5635 Jackson Center');
insert into companies (id, company, city, office_address) values (398, 'Meezzy', 'Tegarenkrajan', '377 Rieder Trail');
insert into companies (id, company, city, office_address) values (399, 'Meeveo', 'Goussainville', '1282 Canary Center');
insert into companies (id, company, city, office_address) values (400, 'Babbleopia', 'Bobon', '872 Melrose Avenue');
insert into companies (id, company, city, office_address) values (401, 'Quinu', 'Zbýšov', '4552 Southridge Way');
insert into companies (id, company, city, office_address) values (402, 'Jatri', 'Chechenglu', '40 Texas Drive');
insert into companies (id, company, city, office_address) values (403, 'Edgewire', 'Cibugel', '88 Debra Parkway');
insert into companies (id, company, city, office_address) values (404, 'Twitterwire', 'Zhenzhushan', '49485 Clarendon Pass');
insert into companies (id, company, city, office_address) values (405, 'Skipfire', 'Svalöv', '3 Twin Pines Hill');
insert into companies (id, company, city, office_address) values (406, 'Demivee', 'Durham', '1 Hazelcrest Parkway');
insert into companies (id, company, city, office_address) values (407, 'Divavu', 'Haoping', '44268 Hooker Avenue');
insert into companies (id, company, city, office_address) values (408, 'Meezzy', 'Eskilstuna', '15 Magdeline Hill');
insert into companies (id, company, city, office_address) values (409, 'Ailane', 'Volodymyr-Volyns’kyy', '8 Southridge Point');
insert into companies (id, company, city, office_address) values (410, 'Topicshots', 'Breda', '28 Marcy Terrace');
insert into companies (id, company, city, office_address) values (411, 'Meeveo', 'Esik', '61388 Stang Street');
insert into companies (id, company, city, office_address) values (412, 'Tazzy', 'La Tuque', '22 Ridgeway Park');
insert into companies (id, company, city, office_address) values (413, 'Rooxo', 'Jiyizhuang', '308 Stuart Point');
insert into companies (id, company, city, office_address) values (414, 'Roombo', 'Molepolole', '72855 7th Road');
insert into companies (id, company, city, office_address) values (415, 'Browsecat', 'Muyaka', '04435 Onsgard Park');
insert into companies (id, company, city, office_address) values (416, 'Shuffletag', 'Cherbourg-Octeville', '19 Briar Crest Place');
insert into companies (id, company, city, office_address) values (417, 'Izio', 'Ibara', '8 Badeau Court');
insert into companies (id, company, city, office_address) values (418, 'Flipopia', 'Gœsdorf', '69 Maple Pass');
insert into companies (id, company, city, office_address) values (419, 'Oloo', 'Jiḩānah', '40 Redwing Park');
insert into companies (id, company, city, office_address) values (420, 'Kwideo', 'Mazyr', '3109 Graedel Plaza');
insert into companies (id, company, city, office_address) values (421, 'Browsebug', 'Santa Catalina', '01756 Washington Parkway');
insert into companies (id, company, city, office_address) values (422, 'Meemm', 'Shanyang', '2 Shoshone Park');
insert into companies (id, company, city, office_address) values (423, 'Tambee', 'Punaauia', '23853 Buell Court');
insert into companies (id, company, city, office_address) values (424, 'Gabtype', 'Kovači', '92049 Claremont Point');
insert into companies (id, company, city, office_address) values (425, 'Linkbridge', 'Libertad', '4 Sauthoff Court');
insert into companies (id, company, city, office_address) values (426, 'Eidel', 'Hegeng', '82740 Oak Center');
insert into companies (id, company, city, office_address) values (427, 'Mydo', 'Magalalag', '6 Memorial Plaza');
insert into companies (id, company, city, office_address) values (428, 'Dabjam', 'Anulid', '51096 Weeping Birch Street');
insert into companies (id, company, city, office_address) values (429, 'Trunyx', 'Trzciana', '862 Fordem Point');
insert into companies (id, company, city, office_address) values (430, 'Lazz', 'Bilhó', '37820 Heath Trail');
insert into companies (id, company, city, office_address) values (431, 'Gabvine', 'Thompson', '54231 Ludington Junction');
insert into companies (id, company, city, office_address) values (432, 'Livefish', 'Huangtan', '34 Bartillon Way');
insert into companies (id, company, city, office_address) values (433, 'Fliptune', 'München', '6 Buell Avenue');
insert into companies (id, company, city, office_address) values (434, 'Twitterworks', 'Ilhéus', '17500 Clemons Alley');
insert into companies (id, company, city, office_address) values (435, 'Kare', 'Dongkan', '629 Michigan Park');
insert into companies (id, company, city, office_address) values (436, 'Skyvu', 'Kuandian', '746 Oriole Street');
insert into companies (id, company, city, office_address) values (437, 'Mydeo', 'Chengjiang', '41889 Namekagon Hill');
insert into companies (id, company, city, office_address) values (438, 'Oba', 'Barra', '13 Golf View Parkway');
insert into companies (id, company, city, office_address) values (439, 'Zoonder', 'Guayabal de Síquima', '92 Mendota Pass');
insert into companies (id, company, city, office_address) values (440, 'Twitternation', 'Orlando', '1 Milwaukee Point');
insert into companies (id, company, city, office_address) values (441, 'Avaveo', 'Amboasary', '5 Delaware Way');
insert into companies (id, company, city, office_address) values (442, 'Meezzy', 'Huangban', '01 Havey Crossing');
insert into companies (id, company, city, office_address) values (443, 'Roombo', 'Östersund', '4 Bartelt Lane');
insert into companies (id, company, city, office_address) values (444, 'Voonyx', 'Pôrto Barra do Ivinheima', '3 Blaine Alley');
insert into companies (id, company, city, office_address) values (445, 'Trunyx', 'Antas', '22621 Esch Alley');
insert into companies (id, company, city, office_address) values (446, 'Jabbertype', 'Ponte Nova', '4843 Towne Street');
insert into companies (id, company, city, office_address) values (447, 'Vinte', 'Ar Rudayyif', '79768 David Circle');
insert into companies (id, company, city, office_address) values (448, 'Thoughtstorm', 'Sudzha', '19 Arrowood Lane');
insert into companies (id, company, city, office_address) values (449, 'Jaxspan', 'Mekarsari', '63208 Havey Pass');
insert into companies (id, company, city, office_address) values (450, 'Skyndu', 'Tilmi', '996 Claremont Drive');
insert into companies (id, company, city, office_address) values (451, 'Agimba', 'Staroutkinsk', '19162 Atwood Center');
insert into companies (id, company, city, office_address) values (452, 'Tekfly', 'San Julian', '349 Burrows Plaza');
insert into companies (id, company, city, office_address) values (453, 'Yoveo', 'Gongji', '288 Graedel Lane');
insert into companies (id, company, city, office_address) values (454, 'Roomm', 'Qingduizi', '600 Cardinal Way');
insert into companies (id, company, city, office_address) values (455, 'Tazz', 'Kỳ Anh', '1564 Ludington Hill');
insert into companies (id, company, city, office_address) values (456, 'Feednation', 'Dadamtu', '38 Burning Wood Alley');
insert into companies (id, company, city, office_address) values (457, 'Topiclounge', 'Pagak', '59 Messerschmidt Trail');
insert into companies (id, company, city, office_address) values (458, 'Divape', 'Ostrowite', '1 Esker Trail');
insert into companies (id, company, city, office_address) values (459, 'Livetube', 'Menzel Abderhaman', '0 Browning Alley');
insert into companies (id, company, city, office_address) values (460, 'Gabtype', 'Vrýses', '383 Daystar Hill');
insert into companies (id, company, city, office_address) values (461, 'Thoughtbeat', 'Yanfolila', '10 Westport Alley');
insert into companies (id, company, city, office_address) values (462, 'Reallinks', 'Baihe', '03 Jay Lane');
insert into companies (id, company, city, office_address) values (463, 'Gigaclub', 'Lapid', '793 Mitchell Drive');
insert into companies (id, company, city, office_address) values (464, 'Topicshots', 'Pasadena', '57556 Dahle Alley');
insert into companies (id, company, city, office_address) values (465, 'Realmix', 'Sulak', '02 Sugar Plaza');
insert into companies (id, company, city, office_address) values (466, 'Avavee', 'General Enrique Godoy', '7839 Erie Point');
insert into companies (id, company, city, office_address) values (467, 'Kayveo', 'Santa Maria', '2827 Elka Trail');
insert into companies (id, company, city, office_address) values (468, 'Skibox', 'Cianorte', '867 Lighthouse Bay Parkway');
insert into companies (id, company, city, office_address) values (469, 'Zazio', 'Banjar Medura', '7 Farragut Place');
insert into companies (id, company, city, office_address) values (470, 'Linkbridge', 'Santo Tomé', '23 Derek Lane');
insert into companies (id, company, city, office_address) values (471, 'Skipfire', 'Glondong', '27 Dixon Point');
insert into companies (id, company, city, office_address) values (472, 'Kwimbee', 'Kamakura', '8 Elka Trail');
insert into companies (id, company, city, office_address) values (473, 'Avamba', 'Zhongxiang', '43196 Coolidge Crossing');
insert into companies (id, company, city, office_address) values (474, 'Flipopia', 'San Antonio', '3 Porter Avenue');
insert into companies (id, company, city, office_address) values (475, 'Youspan', 'Mozi', '47055 Hudson Plaza');
insert into companies (id, company, city, office_address) values (476, 'Gabtune', 'San Antonio', '71 Judy Pass');
insert into companies (id, company, city, office_address) values (477, 'Buzzshare', 'Jefferson City', '15 Browning Circle');
insert into companies (id, company, city, office_address) values (478, 'Geba', 'El Refugio', '7 Ryan Circle');
insert into companies (id, company, city, office_address) values (479, 'Mynte', 'Kitakyūshū', '341 Merrick Park');
insert into companies (id, company, city, office_address) values (480, 'Babbleopia', 'Guangsheng', '6 Sommers Road');
insert into companies (id, company, city, office_address) values (481, 'Youbridge', 'Khon San', '32 Quincy Road');
insert into companies (id, company, city, office_address) values (482, 'Twitternation', 'Sao Hai', '8 La Follette Way');
insert into companies (id, company, city, office_address) values (483, 'Feednation', 'Estrada', '3 Ridge Oak Terrace');
insert into companies (id, company, city, office_address) values (484, 'Realpoint', 'Paitan Este', '94112 Cherokee Parkway');
insert into companies (id, company, city, office_address) values (485, 'Meezzy', 'Tanshi', '6292 Cherokee Street');
insert into companies (id, company, city, office_address) values (486, 'Topicshots', 'Omaha', '137 Clyde Gallagher Street');
insert into companies (id, company, city, office_address) values (487, 'Yambee', 'Arani', '529 Jana Point');
insert into companies (id, company, city, office_address) values (488, 'Digitube', 'Beo', '7404 Bluestem Pass');
insert into companies (id, company, city, office_address) values (489, 'Flashset', 'Mashui', '0 Meadow Vale Terrace');
insert into companies (id, company, city, office_address) values (490, 'Gevee', 'Tajimi', '03 Pepper Wood Junction');
insert into companies (id, company, city, office_address) values (491, 'Skimia', 'Boršice', '520 Utah Street');
insert into companies (id, company, city, office_address) values (492, 'Plajo', 'Wissembourg', '2 Oak Hill');
insert into companies (id, company, city, office_address) values (493, 'Eabox', 'Isdalstø', '37 Superior Pass');
insert into companies (id, company, city, office_address) values (494, 'DabZ', 'Longshan', '8740 Becker Hill');
insert into companies (id, company, city, office_address) values (495, 'Avamba', 'Aghada', '5 Lakewood Junction');
insert into companies (id, company, city, office_address) values (496, 'Aivee', 'Nhơn Trạch', '41398 Arrowood Terrace');
insert into companies (id, company, city, office_address) values (497, 'Avamm', 'Comallo', '204 Mccormick Lane');
insert into companies (id, company, city, office_address) values (498, 'Abatz', 'Vicente Guerrero', '953 Carey Place');
insert into companies (id, company, city, office_address) values (499, 'Jatri', 'Caotan', '9766 Monument Avenue');
insert into companies (id, company, city, office_address) values (500, 'Kayveo', 'Liushikou', '78 Red Cloud Park');
insert into companies (id, company, city, office_address) values (501, 'Jabbersphere', 'Viçosa', '71554 Upham Terrace');
insert into companies (id, company, city, office_address) values (502, 'Gigabox', 'Kudahuvadhoo', '41670 Bartelt Crossing');
insert into companies (id, company, city, office_address) values (503, 'Voomm', 'Marne-la-Vallée', '41 Manitowish Avenue');
insert into companies (id, company, city, office_address) values (504, 'Zava', 'Haoxin', '2938 Straubel Crossing');
insert into companies (id, company, city, office_address) values (505, 'Katz', 'Goya', '89 Maple Terrace');
insert into companies (id, company, city, office_address) values (506, 'Twitterwire', 'Cidolog', '798 Autumn Leaf Place');
insert into companies (id, company, city, office_address) values (507, 'Quatz', 'Panenggoede', '890 Randy Street');
insert into companies (id, company, city, office_address) values (508, 'Tavu', 'Tunjë', '5875 Badeau Hill');
insert into companies (id, company, city, office_address) values (509, 'Dynabox', 'Hausjärvi', '127 Stoughton Court');
insert into companies (id, company, city, office_address) values (510, 'LiveZ', 'Franco da Rocha', '146 Southridge Road');
insert into companies (id, company, city, office_address) values (511, 'Janyx', 'Si Racha', '53 Messerschmidt Street');
insert into companies (id, company, city, office_address) values (512, 'Jaxnation', 'Kotel', '64 Carey Avenue');
insert into companies (id, company, city, office_address) values (513, 'Linklinks', 'Zastron', '15097 Almo Hill');
insert into companies (id, company, city, office_address) values (514, 'Snaptags', 'Torsås', '87 Clarendon Plaza');
insert into companies (id, company, city, office_address) values (515, 'Flashset', 'Gandusari', '544 Debra Place');
insert into companies (id, company, city, office_address) values (516, 'Oloo', 'Xinpeicun', '8851 Gateway Hill');
insert into companies (id, company, city, office_address) values (517, 'Flashdog', 'Călăraşi', '46814 Ronald Regan Trail');
insert into companies (id, company, city, office_address) values (518, 'Fanoodle', 'Parnaíba', '295 Anhalt Street');
insert into companies (id, company, city, office_address) values (519, 'Kanoodle', 'Calsib', '4 Kropf Drive');
insert into companies (id, company, city, office_address) values (520, 'Zoombeat', 'Hongjiaguan', '3 Heffernan Trail');
insert into companies (id, company, city, office_address) values (521, 'Jabbercube', 'Jingouhe', '45 Lunder Park');
insert into companies (id, company, city, office_address) values (522, 'Livetube', 'Pag', '0316 Duke Drive');
insert into companies (id, company, city, office_address) values (523, 'Linkbuzz', 'Santo António das Areias', '88183 Lukken Alley');
insert into companies (id, company, city, office_address) values (524, 'Tanoodle', 'Maqia', '861 Colorado Plaza');
insert into companies (id, company, city, office_address) values (525, 'Edgeblab', 'Betioky', '7422 Victoria Circle');
insert into companies (id, company, city, office_address) values (526, 'Wordware', 'Quankou', '42 Continental Lane');
insert into companies (id, company, city, office_address) values (527, 'Dazzlesphere', 'Huangzhuang', '7349 High Crossing Terrace');
insert into companies (id, company, city, office_address) values (528, 'Topdrive', 'Ternopil’', '6 Portage Circle');
insert into companies (id, company, city, office_address) values (529, 'Thoughtsphere', 'Konstancin-Jeziorna', '885 Lien Parkway');
insert into companies (id, company, city, office_address) values (530, 'Tagopia', 'Kafr Şaqr', '2 Monica Lane');
insert into companies (id, company, city, office_address) values (531, 'Kayveo', 'Jiangzhou', '401 Bartillon Plaza');
insert into companies (id, company, city, office_address) values (532, 'Blogpad', 'Balin', '46 Crownhardt Place');
insert into companies (id, company, city, office_address) values (533, 'Abatz', 'Masaraway', '27 Eagan Drive');
insert into companies (id, company, city, office_address) values (534, 'Voomm', 'Alepoú', '802 Park Meadow Avenue');
insert into companies (id, company, city, office_address) values (535, 'Youspan', 'Zaoshi', '160 Gina Place');
insert into companies (id, company, city, office_address) values (536, 'Talane', 'Qingshuihe', '34842 Jenifer Hill');
insert into companies (id, company, city, office_address) values (537, 'Wordtune', 'Niamtougou', '85 Lakewood Gardens Lane');
insert into companies (id, company, city, office_address) values (538, 'Rhyloo', 'Tsotsin-Yurt', '967 Lerdahl Road');
insert into companies (id, company, city, office_address) values (539, 'Eabox', 'Kuwait City', '2034 Sutteridge Alley');
insert into companies (id, company, city, office_address) values (540, 'Feedmix', 'Gaborone', '0 Redwing Center');
insert into companies (id, company, city, office_address) values (541, 'Skajo', 'Bayan Huxu', '5 Rigney Pass');
insert into companies (id, company, city, office_address) values (542, 'Flashdog', 'Solnechnyy', '9 Spenser Parkway');
insert into companies (id, company, city, office_address) values (543, 'Livepath', 'Kiraman', '0 Cordelia Hill');
insert into companies (id, company, city, office_address) values (544, 'Rhycero', 'Perelhal', '6224 Helena Avenue');
insert into companies (id, company, city, office_address) values (545, 'Thoughtblab', 'Pule', '1349 Division Center');
insert into companies (id, company, city, office_address) values (546, 'Wordify', 'Labuhan', '754 Mallory Trail');
insert into companies (id, company, city, office_address) values (547, 'Topiczoom', 'Nantang', '3004 Tennyson Pass');
insert into companies (id, company, city, office_address) values (548, 'Youbridge', 'Ryūō', '18 Drewry Center');
insert into companies (id, company, city, office_address) values (549, 'Shufflebeat', 'Shijing', '2 Florence Parkway');
insert into companies (id, company, city, office_address) values (550, 'Avamm', 'Kuching', '98 Ridge Oak Point');
insert into companies (id, company, city, office_address) values (551, 'Zooveo', 'Nariño', '85238 Prentice Trail');
insert into companies (id, company, city, office_address) values (552, 'Twinte', 'Talok', '55123 Carioca Lane');
insert into companies (id, company, city, office_address) values (553, 'Cogidoo', 'Timezgadiouine', '0808 Bashford Crossing');
insert into companies (id, company, city, office_address) values (554, 'Zava', 'Mira', '93 Westerfield Trail');
insert into companies (id, company, city, office_address) values (555, 'Tagcat', 'Mojokerto', '5741 Eastlawn Pass');
insert into companies (id, company, city, office_address) values (556, 'Skidoo', 'Ōdachō-ōda', '01 Maple Wood Plaza');
insert into companies (id, company, city, office_address) values (557, 'Photobug', 'Ukata', '871 Ruskin Place');
insert into companies (id, company, city, office_address) values (558, 'Izio', 'Nikol’sk', '4535 Thompson Court');
insert into companies (id, company, city, office_address) values (559, 'Topiczoom', 'Lazarevac', '635 Melody Street');
insert into companies (id, company, city, office_address) values (560, 'Fivechat', 'Fangxiang', '93 Merry Street');
insert into companies (id, company, city, office_address) values (561, 'Jayo', 'Bin Yauri', '04 Sunfield Trail');
insert into companies (id, company, city, office_address) values (562, 'Devify', 'Jalingo', '03 Monica Crossing');
insert into companies (id, company, city, office_address) values (563, 'Flipstorm', 'Quintã', '2857 Claremont Alley');
insert into companies (id, company, city, office_address) values (564, 'Livetube', 'Tópaga', '45 Arizona Drive');
insert into companies (id, company, city, office_address) values (565, 'Chatterbridge', 'Emmen', '26618 Cambridge Pass');
insert into companies (id, company, city, office_address) values (566, 'Roodel', 'Guizi', '9 Graedel Drive');
insert into companies (id, company, city, office_address) values (567, 'Vitz', 'Vin’kivtsi', '1 Bellgrove Way');
insert into companies (id, company, city, office_address) values (568, 'Reallinks', 'Naghalin', '367 Graedel Place');
insert into companies (id, company, city, office_address) values (569, 'Devshare', 'Bulakbanjar', '2683 Warner Trail');
insert into companies (id, company, city, office_address) values (570, 'Oyoba', 'Sammatti', '07 Dahle Pass');
insert into companies (id, company, city, office_address) values (571, 'Blognation', 'Bremen', '41745 Sundown Way');
insert into companies (id, company, city, office_address) values (572, 'Katz', 'Moramanga', '27205 Quincy Junction');
insert into companies (id, company, city, office_address) values (573, 'Babbleset', 'Tlogowetan', '46 Briar Crest Court');
insert into companies (id, company, city, office_address) values (574, 'Camimbo', 'Shigu', '25 Reinke Hill');
insert into companies (id, company, city, office_address) values (575, 'Trilia', 'Balfour', '78 Truax Circle');
insert into companies (id, company, city, office_address) values (576, 'Fadeo', 'Tiabaya', '64 Leroy Park');
insert into companies (id, company, city, office_address) values (577, 'Dynabox', 'Zamora', '7 Merrick Lane');
insert into companies (id, company, city, office_address) values (578, 'Tagopia', 'Cordeiro', '80248 Waubesa Center');
insert into companies (id, company, city, office_address) values (579, 'Oyoba', 'Aleksotas', '918 Amoth Alley');
insert into companies (id, company, city, office_address) values (580, 'Jabberbean', 'Homa Bay', '561 School Way');
insert into companies (id, company, city, office_address) values (581, 'Plajo', 'Alofi', '2 Cambridge Way');
insert into companies (id, company, city, office_address) values (582, 'Snaptags', 'Kampungtengah', '112 Dovetail Pass');
insert into companies (id, company, city, office_address) values (583, 'Skipfire', 'Xitou', '082 Gale Drive');
insert into companies (id, company, city, office_address) values (584, 'Twitterlist', 'Los Nogales', '4611 Jackson Crossing');
insert into companies (id, company, city, office_address) values (585, 'Skalith', 'Margahayukencana', '06024 Nobel Avenue');
insert into companies (id, company, city, office_address) values (586, 'Twiyo', 'Seremban', '8540 Clemons Center');
insert into companies (id, company, city, office_address) values (587, 'Izio', 'Semenivka', '8 Bartelt Park');
insert into companies (id, company, city, office_address) values (588, 'Skyndu', 'Takāb', '1318 Kim Hill');
insert into companies (id, company, city, office_address) values (589, 'Flashset', 'Ipoh', '136 Pine View Court');
insert into companies (id, company, city, office_address) values (590, 'Twinte', 'Ampanihy', '5 Messerschmidt Junction');
insert into companies (id, company, city, office_address) values (591, 'Skinte', 'La Soledad', '17722 Vahlen Road');
insert into companies (id, company, city, office_address) values (592, 'Jabbersphere', 'Chafé', '61731 Truax Point');
insert into companies (id, company, city, office_address) values (593, 'Linklinks', 'Monteiro', '92960 Vermont Center');
insert into companies (id, company, city, office_address) values (594, 'Cogibox', 'Riang Tengah', '75238 Chinook Circle');
insert into companies (id, company, city, office_address) values (595, 'Livefish', 'Saraktash', '5 Hooker Court');
insert into companies (id, company, city, office_address) values (596, 'Oyoyo', 'Clarines', '7815 Victoria Hill');
insert into companies (id, company, city, office_address) values (597, 'Ainyx', 'Fengshuling', '17337 Ronald Regan Lane');
insert into companies (id, company, city, office_address) values (598, 'Zoonder', 'Khānewāl', '46868 Armistice Road');
insert into companies (id, company, city, office_address) values (599, 'Kazu', 'Hōjō', '763 Dottie Way');
insert into companies (id, company, city, office_address) values (600, 'Topicware', 'Quinta de Valadares', '24 Raven Junction');
